FROM ubuntu:20.04

ADD ./install-dependencies.sh /tmp/install-dependencies.sh
RUN apt-get update -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y git sudo pkg-config ccache && \
    bash /tmp/install-dependencies.sh 
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y g++-12 && \
    update-alternatives \
    --install /usr/bin/gcc gcc /usr/bin/gcc-12 60 \
    --slave /usr/bin/g++ g++ /usr/bin/g++-12 && \
    update-alternatives --auto gcc
